name: Upload and Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Build your project here
      
      # Example: Build a JAR file
      - name: Build JAR
        run: mvn package -DskipTests

      - name: Move JAR to Different Folder
        run: mv /home/runner/work/IITB-Backen-AST/IITB-Backen-AST/target/IITB-0.0.1-SNAPSHOT.jar /src/main

      # Upload artifact
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-artifact
      #     path:  /home/runner/work/IITB-Backen-AST/IITB-Backen-AST/target/IITB-0.0.1-SNAPSHOT.jar

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #     # Download artifact
  #     - name: Download artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: my-artifact
  #         path: deployArtifact

      # Deploy your artifact
      # Add your deployment steps here
