name: Upload and Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build your project here
      
      # Example: Build a JAR file
      - name: Build JAR
        run: mvn package -DskipTests

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifact.jar

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      # Deploy your artifact
      # Add your deployment steps here
